spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/jeommechu  # 데이터베이스 이름을 your_database_name으로 바꿉니다.
    driver-class-name: org.mariadb.jdbc.Driver # MariaDB 드라이버 클래스 이름
    username: jmc  # MariaDB 사용자 이름으로 바꿉니다.
    password: qwer1234  # MariaDB 비밀번호로 바꿉니다.

  jpa:
    hibernate:
      ddl-auto: update # DDL 자동 업데이트 설정
    show-sql: true # SQL 쿼리 로그 표시 여부
    properties:
      hibernate:
        format_sql: true # SQL 쿼리 포맷팅 설정