spring:
  datasource:
    url: jdbc:h2:mem:jemmechu  # ???? H2 ??????? JDBC URL. ???? ??? 'jemmechu'?? ??????? ?????.
    driver-class-name: org.h2.Driver  # H2 ?????? ???? ????
    username: sa  # H2 ??????? ?? ???? (???: sa)
    password:  # ???? ?? (H2? ?? ????? ????)

  h2:
    console:
      enabled: true  # H2 ??? ??????. ? ??? ?????? ?? ??? ??? ? ?? ????.
      path: /h2-console  # H2 ??? ???? ?? ?? ??

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update  # Hibernate? ?????? ???? ???? ??????? ?????.
    show-sql: true  # ???? SQL ??? ??? ????? ?????.
    properties:
      hibernate:
        format_sql: true

