spring:
  datasource:
#    url: jdbc:mariadb://localhost:3306/jeommechu
    url: jdbc:mariadb://52.78.113.103:3306/jeommechu
    driver-class-name: org.mariadb.jdbc.Driver
    username: jmc
    password: qwer1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace