spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/jeommechu
#    url: jdbc:mariadb://52.78.113.103:3306/jeommechu
    driver-class-name: org.mariadb.jdbc.Driver
    username: jmc
    password: qwer1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: info
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
  file:
    name: logs/jmc.log  # 로그 파일 경로 설정
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} [%file:%line %M] - %msg%n%ex{short}" # 콘솔 로그 포맷
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} [%file:%line %M] - %msg%n%ex" # 파일 로그 포맷
  logback:
    rollingPolicy:
      max-file-size: 10MB
      max-history: 30

kakao:
  client-id: ${KAKAO_CLIENT_ID}
  redirect-url: ${KAKAO_REDIRECT_URL}
  token-url: https://kauth.kakao.com/oauth/token
  user-info-url: https://kapi.kakao.com/v2/user/me

jwt:
  secret-key: wjaapcbWkdWKdaosgksjaqorhvmekdngkgk970127g